; PlatformIO Project Configuration File for RT-Spark (STM32F407ZGT6)
; BCA182 Laboratory Activity 3 - Activity Recognition
[platformio]
default_envs = rt_spark_f407

[env:rt_spark_f407]
platform = ststm32
board = black_f407zg
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

build_flags =
    -DUSE_HAL_DRIVER
    -DSTM32F407xx
    -DHSE_VALUE=8000000
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
    -Iinclude
    -IRTE/CMSIS_Driver

lib_deps =
    bojit/PlatformIO-FreeRTOS@^2.1.4

[env:native]
platform = native
test_framework = unity
build_flags =
    -Iinclude
    -DNATIVE_TEST
